// Generated by gencpp from file qt_tutorials/TwoInts.msg
// DO NOT EDIT!


#ifndef QT_TUTORIALS_MESSAGE_TWOINTS_H
#define QT_TUTORIALS_MESSAGE_TWOINTS_H

#include <ros/service_traits.h>


#include <qt_tutorials/TwoIntsRequest.h>
#include <qt_tutorials/TwoIntsResponse.h>


namespace qt_tutorials
{

struct TwoInts
{

typedef TwoIntsRequest Request;
typedef TwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TwoInts
} // namespace qt_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_tutorials::TwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::qt_tutorials::TwoInts&) { return value(); }
};

template<>
struct DataType< ::qt_tutorials::TwoInts > {
  static const char* value()
  {
    return "qt_tutorials/TwoInts";
  }

  static const char* value(const ::qt_tutorials::TwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::qt_tutorials::TwoIntsRequest> should match 
// service_traits::MD5Sum< ::qt_tutorials::TwoInts > 
template<>
struct MD5Sum< ::qt_tutorials::TwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_tutorials::TwoInts >::value();
  }
  static const char* value(const ::qt_tutorials::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_tutorials::TwoIntsRequest> should match 
// service_traits::DataType< ::qt_tutorials::TwoInts > 
template<>
struct DataType< ::qt_tutorials::TwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::qt_tutorials::TwoInts >::value();
  }
  static const char* value(const ::qt_tutorials::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_tutorials::TwoIntsResponse> should match 
// service_traits::MD5Sum< ::qt_tutorials::TwoInts > 
template<>
struct MD5Sum< ::qt_tutorials::TwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_tutorials::TwoInts >::value();
  }
  static const char* value(const ::qt_tutorials::TwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_tutorials::TwoIntsResponse> should match 
// service_traits::DataType< ::qt_tutorials::TwoInts > 
template<>
struct DataType< ::qt_tutorials::TwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::qt_tutorials::TwoInts >::value();
  }
  static const char* value(const ::qt_tutorials::TwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_TUTORIALS_MESSAGE_TWOINTS_H
