// Generated by gencpp from file zed_interfaces/reset_tracking.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_RESET_TRACKING_H
#define ZED_INTERFACES_MESSAGE_RESET_TRACKING_H

#include <ros/service_traits.h>


#include <zed_interfaces/reset_trackingRequest.h>
#include <zed_interfaces/reset_trackingResponse.h>


namespace zed_interfaces
{

struct reset_tracking
{

typedef reset_trackingRequest Request;
typedef reset_trackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_tracking
} // namespace zed_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zed_interfaces::reset_tracking > {
  static const char* value()
  {
    return "e1e87fc9e9e6c154eca93b9fa292cc05";
  }

  static const char* value(const ::zed_interfaces::reset_tracking&) { return value(); }
};

template<>
struct DataType< ::zed_interfaces::reset_tracking > {
  static const char* value()
  {
    return "zed_interfaces/reset_tracking";
  }

  static const char* value(const ::zed_interfaces::reset_tracking&) { return value(); }
};


// service_traits::MD5Sum< ::zed_interfaces::reset_trackingRequest> should match 
// service_traits::MD5Sum< ::zed_interfaces::reset_tracking > 
template<>
struct MD5Sum< ::zed_interfaces::reset_trackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::reset_tracking >::value();
  }
  static const char* value(const ::zed_interfaces::reset_trackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::reset_trackingRequest> should match 
// service_traits::DataType< ::zed_interfaces::reset_tracking > 
template<>
struct DataType< ::zed_interfaces::reset_trackingRequest>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::reset_tracking >::value();
  }
  static const char* value(const ::zed_interfaces::reset_trackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zed_interfaces::reset_trackingResponse> should match 
// service_traits::MD5Sum< ::zed_interfaces::reset_tracking > 
template<>
struct MD5Sum< ::zed_interfaces::reset_trackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::reset_tracking >::value();
  }
  static const char* value(const ::zed_interfaces::reset_trackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::reset_trackingResponse> should match 
// service_traits::DataType< ::zed_interfaces::reset_tracking > 
template<>
struct DataType< ::zed_interfaces::reset_trackingResponse>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::reset_tracking >::value();
  }
  static const char* value(const ::zed_interfaces::reset_trackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_RESET_TRACKING_H
