// Generated by gencpp from file zed_interfaces/reset_odometry.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_RESET_ODOMETRY_H
#define ZED_INTERFACES_MESSAGE_RESET_ODOMETRY_H

#include <ros/service_traits.h>


#include <zed_interfaces/reset_odometryRequest.h>
#include <zed_interfaces/reset_odometryResponse.h>


namespace zed_interfaces
{

struct reset_odometry
{

typedef reset_odometryRequest Request;
typedef reset_odometryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_odometry
} // namespace zed_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zed_interfaces::reset_odometry > {
  static const char* value()
  {
    return "e1e87fc9e9e6c154eca93b9fa292cc05";
  }

  static const char* value(const ::zed_interfaces::reset_odometry&) { return value(); }
};

template<>
struct DataType< ::zed_interfaces::reset_odometry > {
  static const char* value()
  {
    return "zed_interfaces/reset_odometry";
  }

  static const char* value(const ::zed_interfaces::reset_odometry&) { return value(); }
};


// service_traits::MD5Sum< ::zed_interfaces::reset_odometryRequest> should match 
// service_traits::MD5Sum< ::zed_interfaces::reset_odometry > 
template<>
struct MD5Sum< ::zed_interfaces::reset_odometryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::reset_odometry >::value();
  }
  static const char* value(const ::zed_interfaces::reset_odometryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::reset_odometryRequest> should match 
// service_traits::DataType< ::zed_interfaces::reset_odometry > 
template<>
struct DataType< ::zed_interfaces::reset_odometryRequest>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::reset_odometry >::value();
  }
  static const char* value(const ::zed_interfaces::reset_odometryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zed_interfaces::reset_odometryResponse> should match 
// service_traits::MD5Sum< ::zed_interfaces::reset_odometry > 
template<>
struct MD5Sum< ::zed_interfaces::reset_odometryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::reset_odometry >::value();
  }
  static const char* value(const ::zed_interfaces::reset_odometryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::reset_odometryResponse> should match 
// service_traits::DataType< ::zed_interfaces::reset_odometry > 
template<>
struct DataType< ::zed_interfaces::reset_odometryResponse>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::reset_odometry >::value();
  }
  static const char* value(const ::zed_interfaces::reset_odometryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_RESET_ODOMETRY_H
