// Generated by gencpp from file zed_interfaces/stop_remote_stream.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_STOP_REMOTE_STREAM_H
#define ZED_INTERFACES_MESSAGE_STOP_REMOTE_STREAM_H

#include <ros/service_traits.h>


#include <zed_interfaces/stop_remote_streamRequest.h>
#include <zed_interfaces/stop_remote_streamResponse.h>


namespace zed_interfaces
{

struct stop_remote_stream
{

typedef stop_remote_streamRequest Request;
typedef stop_remote_streamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stop_remote_stream
} // namespace zed_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zed_interfaces::stop_remote_stream > {
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::zed_interfaces::stop_remote_stream&) { return value(); }
};

template<>
struct DataType< ::zed_interfaces::stop_remote_stream > {
  static const char* value()
  {
    return "zed_interfaces/stop_remote_stream";
  }

  static const char* value(const ::zed_interfaces::stop_remote_stream&) { return value(); }
};


// service_traits::MD5Sum< ::zed_interfaces::stop_remote_streamRequest> should match 
// service_traits::MD5Sum< ::zed_interfaces::stop_remote_stream > 
template<>
struct MD5Sum< ::zed_interfaces::stop_remote_streamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::stop_remote_stream >::value();
  }
  static const char* value(const ::zed_interfaces::stop_remote_streamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::stop_remote_streamRequest> should match 
// service_traits::DataType< ::zed_interfaces::stop_remote_stream > 
template<>
struct DataType< ::zed_interfaces::stop_remote_streamRequest>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::stop_remote_stream >::value();
  }
  static const char* value(const ::zed_interfaces::stop_remote_streamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zed_interfaces::stop_remote_streamResponse> should match 
// service_traits::MD5Sum< ::zed_interfaces::stop_remote_stream > 
template<>
struct MD5Sum< ::zed_interfaces::stop_remote_streamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::stop_remote_stream >::value();
  }
  static const char* value(const ::zed_interfaces::stop_remote_streamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::stop_remote_streamResponse> should match 
// service_traits::DataType< ::zed_interfaces::stop_remote_stream > 
template<>
struct DataType< ::zed_interfaces::stop_remote_streamResponse>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::stop_remote_stream >::value();
  }
  static const char* value(const ::zed_interfaces::stop_remote_streamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_STOP_REMOTE_STREAM_H
