%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 1208.226731
Camera.fy: 1205.548227
Camera.cx: 305.863428
Camera.cy: 283.394157

Camera.k1: -0.087742
Camera.k2: 0.374604
Camera.p1: 0.000112
Camera.p2: 0.000612
Camera.k3: 0.000000

Camera.width: 544
Camera.height: 544

# Camera frames per second
Camera.fps: 30.0

# stereo baseline times fx
Camera.bf: 86.14365333630209

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Close/Far threshold. Baseline times.
ThDepth: 25

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 4
